### ISSUE TITLE
Can no longer navigate to new user registration page!

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#198]
https://sentry.io/environmental-data-governance-/db-prod/issues/435386093/

```
NoMethodError: undefined method `email' for nil:NilClass
  app/controllers/users/registrations_controller.rb:9:in `block in new'
    user.email = @invitation.email if @invitation.email.present?
  app/controllers/users/registrations_controller.rb:8:in `new'
    super do |user|
...
(90 additional frame(s) were not displayed)

NoMethodError: undefined method `email' for nil:NilClass
```

I’m betting this occurred in the Devise 4.3 → 4.4 upgrade last week: https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/189

Hopefully it’s something fairly simple. Should add an integration test to make sure this page can load.

**Comment by Mr0grog** [comment]
…actually, this doesn’t look like it would have *ever* worked (it breaks if you come to the page without an invite code in the URL). Maybe I didn’t worry about it initially because you have to have an invite to sign up with anyhow.
