### ISSUE TITLE
Creating annotations for the first version of a page should be a 400 error

### ISSUE THREAD

**Issue by KrzysztofMadejski** [edgi-govdata-archiving/web-monitoring-db#81]
- I'm operating on seed data.
- In UI I've opened first link
- I've clicked Update Record
- I got following error:

```
Started POST "/api/v0/pages/9c1b56f8-b044-47f4-8d1e-1cea8be1788a/versions/50b2b776-3390-4f94-ae6c-da988a514087/annotations" for 127.0.0.1 at 2017-06-09 13:47:33 +0200
Processing by Api::V0::AnnotationsController#create as */*
  Parameters: {"page_id"=>"9c1b56f8-b044-47f4-8d1e-1cea8be1788a", "version_id"=>"50b2b776-3390-4f94-ae6c-da988a514087"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "seed-admin@example.com"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
  SQL (0.3ms)  UPDATE "users" SET "current_sign_in_at" = $1, "last_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 WHERE "users"."id" = $5  [["current_sign_in_at", "2017-06-09 11:47:34.068000"], ["last_sign_in_at", "2017-06-09 11:47:15.051779"], ["sign_in_count", 3], ["updated_at", "2017-06-09 11:47:34.068546"], ["id", 1]]
   (1.2ms)  COMMIT
  Version Load (0.2ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."uuid" = $1 LIMIT $2  [["uuid", "50b2b776-3390-4f94-ae6c-da988a514087"], ["LIMIT", 1]]
  Page Load (0.1ms)  SELECT  "pages".* FROM "pages" WHERE "pages"."uuid" = $1 LIMIT $2  [["uuid", "9c1b56f8-b044-47f4-8d1e-1cea8be1788a"], ["LIMIT", 1]]
  Version Load (0.2ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."page_uuid" = $1 AND (capture_time < '2017-05-09 10:48:44') ORDER BY "versions"."capture_time" DESC LIMIT $2  [["page_uuid", "9c1b56f8-b044-47f4-8d1e-1cea8be1788a"], ["LIMIT", 1]]
  Change Load (0.2ms)  SELECT  "changes".* FROM "changes" WHERE "changes"."uuid_from" IS NULL AND "changes"."uuid_to" = '50b2b776-3390-4f94-ae6c-da988a514087' ORDER BY "changes"."uuid" ASC LIMIT $1  [["LIMIT", 1]]
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 139ms (ActiveRecord: 3.2ms)


  
NoMethodError (undefined method `capture_time' for nil:NilClass):
  
app/models/change.rb:79:in `from_must_be_before_to_version'
app/models/change.rb:36:in `annotate'
app/controllers/api/v0/annotations_controller.rb:28:in `create'

```

**Comment by Mr0grog** [comment]
I can’t tell for sure because UUIDs are created when importing and are not present in the seed data, but this looks like an expected error—the main bug is on the UI side. Most versions in the seed data are not annotatable (we should probably make new seed data where that’s not the case).

However, we *should* surface a clearer error in this case (and it should be a 400, not 500, error). What’s actually happening is that annotations are on *changes,* not versions. Annotating a version is really a shortcut for annotating the change between a version and its previous version. What you’re seeing here looks like a change couldn’t be created because there is no previous version (hence the `nil` error).

On the DB side, we should return a 400 error (probably an instance of `Api::InputError`) because this version is actually not eligible for annotation.

On the UI side, a request to annotate should simply never be made for the initial version of a page.
