### ISSUE TITLE
Add javascript runtime requirment to installation or troubleshooting instructions

### ISSUE THREAD

**Issue by michardy** [edgi-govdata-archiving/web-monitoring-db#90]
I think that it might be helpful to in some way indicate in the installation instructions that a JavaScript runtime, such as NodeJS, is required.  If you do not have a runtime installed you will get this:

``` bash
web-monitoring-db $ bundle exec rake db:setup
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
Backtrace for gem load error is:
/usr/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/usr/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/usr/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
/usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/usr/lib/ruby/gems/2.4.0/gems/uglifier-3.2.0/lib/uglifier.rb:5:in `<top (required)>'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/home/michael/Code/web-monitoring-db/config/application.rb:7:in `<top (required)>'
/home/michael/Code/web-monitoring-db/Rakefile:5:in `require_relative'
/home/michael/Code/web-monitoring-db/Rakefile:5:in `<top (required)>'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/bin/rake:22:in `load'
/usr/bin/rake:22:in `<top (required)>'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/home/michael/.gem/ruby/2.4.0/bin/bundle:22:in `load'
/home/michael/.gem/ruby/2.4.0/bin/bundle:22:in `<main>'
Bundler Error Backtrace:
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/home/michael/Code/web-monitoring-db/config/application.rb:7:in `<top (required)>'
/home/michael/Code/web-monitoring-db/Rakefile:5:in `require_relative'
/home/michael/Code/web-monitoring-db/Rakefile:5:in `<top (required)>'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/home/michael/.gem/ruby/2.4.0/bin/bundle:22:in `load'
/home/michael/.gem/ruby/2.4.0/bin/bundle:22:in `<main>'
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/home/michael/Code/web-monitoring-db/config/application.rb:7:in `<top (required)>'
/home/michael/Code/web-monitoring-db/Rakefile:5:in `require_relative'
/home/michael/Code/web-monitoring-db/Rakefile:5:in `<top (required)>'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/michael/.gem/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/home/michael/.gem/ruby/2.4.0/bin/bundle:22:in `load'
/home/michael/.gem/ruby/2.4.0/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```
While the error does link to an explanation, it is good practice to list all dependencies in installation instructions.  Also, ruby buries that link at the in a very long stack trace.

**Comment by michardy** [comment]
Created pull request #92 to fix this issue
